# Generated by Django 3.2.8 on 2023-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220204_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
