# Generated by Django 4.2.5 on 2023-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
    ]
