# Generated by Django 4.2.5 on 2023-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timeStamp",
            field=models.DateTimeField(blank=True),
        ),
    ]
